---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  labels:
    app: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usersvc
  template:  # This line should be aligned under `spec`, not `selector`
    metadata:
      labels:
        app: usersvc
    spec:
      containers:
        - name: web
          image: shaikkhajaibrahim/libuserssvc:1.0
          envFrom: 
            - configMapRef:
                name: usersvc-configmap 
          resources:
            requests:
              memory: "24Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  labels:
    app: users-service
spec:
  type: NodePort
  selector:
    app: usersvc
  ports:
    - port: 8000
      targetPort: 8000
