#secret map for booksdb
---
apiVersion: v1
kind: Secret
metadata: 
  name: booksdb-secrets
data:
  POSTGRES_USER: dXNlcg== #user
  POSTGRES_PASSWORD: cGFzc3dvcmQ= #password
  POSTGRES_DB: Ym9va3NkYg== #booksdb


#secret map for book-service
---
apiVersion: v1
kind: Secret
metadata:
  name: booksdb-svc-secrets
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAYm9va3NkYi0xLmJvb2tzZGJzdHMtc3ZjOjU0MzIvYm9va3NkYg==
  SECRET_KEY: WXRERVZXbkwzNWFBSVAtNXl4ZUxqQVo0OVI5MjAtbU1ORGZ3UHlXVUx1NjNIRnNZem8wZi1MTzJJbnhDOGV1NDI4aw==


#secrets map for userdb
---
apiVersion: v1
kind: Secret
metadata:
  name: usersdb-secrets
data:
  POSTGRES_USER: dXNlcg== #user
  POSTGRES_PASSWORD: cGFzc3dvcmQ= #password
  POSTGRES_DB: dXNlcnNkYg==  #usersdb

#secrets map of users-svc
---
apiVersion: v1
kind: Secret
metadata:
  name: usersdb-svc-secrets
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAdXNlcnNkYi0xLnVzZXJzZGJzdHMtc3ZjOjU0MzIvdXNlcnNkYg==
  SECRET_KEY: WXRERVZXbkwzNWFBSVAtNXl4ZUxqQVo0OVI5MjAtbU1ORGZ3UHlXVUx1NjNIRnNZem8wZi1MTzJJbnhDOGV1NDI4aw==






