#secret map for booksdb
---
apiVersion: v1
kind: Secret
metadata: 
  name: booksdb-secrets
data:
  POSTGRES_USER: dXNlcg== #user
  POSTGRES_PASSWORD: cGFzc3dvcmQ= #password
  POSTGRES_DB: Ym9va3NkYg==


#secret map for book-service
---
apiVersion: v1
kind: Secret
metadata:
  name: booksdb-svc-secrets
data:
DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAYm9va3NkYi0xLmJvb2tzZGItc2VydmljZTo1NDMyL2Jvb2tzZGI=
SECRET_KEY: WXRERVZXbkwzNWFBSVAtNXl4ZUxqQVo0OVI5MjAtbU1ORGZ3UHlXVUx1NjNIRnNZem8wZi1MTzJJbnhDOGV1NDI4aw==