# Secrets for bookdb database
---
apiVersion: v1
kind: Secret
metadata:
  name: booksdb-sts
data:
  POSTGRES_USER: dXNlcgo=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_DB: Ym9va3NkYgo=

# secrets for userdb datbase
---
apiVersion: v1
kind: Secret
metadata:
  name: usersdb-sts
data:
  POSTGRES_USER: dXNlcgo=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_DB: Ym9va3NkYgo=

