# Secrets for bookdb database
---
apiVersion: v1
kind: Secret
metadata:
  name: booksdb-sts
data:
  POSTGRES_USER: dXNlcgo=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_DB: Ym9va3NkYgo=

# secrets for userdb datbase
---
apiVersion: v1
kind: Secret
metadata:
  name: usersdb-sts
data:
  POSTGRES_USER: dXNlcgo=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_DB: Ym9va3NkYgo=

---
apiVersion: v1
kind: Secret
metadata:
  name: booksdb-svc-secrets
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAYm9va3NkYnN0cy1zdmM6NTQzMi9ib29rc2Ri
  SECRET_KEY: WXRERVZXbkwzNWFBSVAtNXl4ZUxqQVo0OVI5MjAtbU1ORGZ3UHlXVUx1NjNIRnNZem8wZi1MTzJJbnhDOGV1NDI4aw==
