---
apiVersion: v1
kind: Secret
metadata:
  name: booksdb-sts
data:
  POSTGRES_USER: dXNlcgo=  # Base64 for 'user'
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # Base64 for 'password'
  POSTGRES_DB: Ym9va3NkYgo=  # Base64 for 'booksdb'

#service for bookdb
---
apiVersion: v1
kind: Secret
metadata:
  name: booksdb-svc-secrets
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAYm9va3NkYnN0cy1zdmM6NTQzMi9ib29rc2Ri
  SECRET_KEY: WXRERVZXbkwzNWFBSVAtNXl4ZUxqQVo0OVI5MjAtbU1ORGZ3UHlXVUx1NjNIRnNZem8wZi1MTzJJbnhDOGV1NDI4aw==


# secrets for userdb datbase
---
apiVersion: v1
kind: Secret
metadata:
  name: usersdb-sts
data:
  POSTGRES_USER: dXNlcgo=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_DB: dXNlcnNkYg==

#service for usersdb
---
apiVersion: v1
kind: Secret
metadata:
  name: usersdb-svc-secrets
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAdXNlcnNkYnN0cy1zdmM6NTQzMi91c2Vyc2Ri
  SECRET_KEY: WXRERVZXbkwzNWFBSVAtNXl4ZUxqQVo0OVI5MjAtbU1ORGZ3UHlXVUx1NjNIRnNZem8wZi1MTzJJbnhDOGV1NDI4aw==
