---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-sts-svc
  labels:
    app:  users-sts-svc
spec: 
  minReadySeconds: 5
  ordinals:
    start: 1
  replicas: 1
  selector:
    matchLabels:
      app: users
  serviceName: usersdb-service
  template:
    metadata:
      labels:
        app: users
        env: dev
    spec: 
      containers:
        - name: web
          image: shaikkhajaibrahim/libuserssvc:1.0
          envFrom:
            - secretRef:
                name: usersdb-svc-secrets
            
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 250m
              memory: 250Mi  
---
apiVersion: v1
kind: Service
metadata:
  name: usersdb-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: users
